name: CI for JavaScript Modules

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Fix Jest permission issue
        run: chmod +x ./node_modules/.bin/mocha || true

      - name: Run Tests for Module 1
        run: npm run test:module1

      - name: Run Tests for Module 2
        run: npm run test:module2

      - name: Run Tests for Module 3
        run: npm run test:module3
